name: 'Auto Create Pull Request'
description: 'Automatically Creates Pull Requests'
author: Flavio Rocha
branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  origin-branch:
    description: 'Origin branch. If blank it will assume the workflow branch.'
    required: false
  target-branch:
    description: 'Target branch'
    required: true
  custom-title:
    description: 'PR title'
    required: false
    default: 'PR created automatically.'
  custom-body:
    description: 'PR body message'
    required: false

runs:
  using: "composite"
  steps:
    steps:
  - run: |
      if [ -z "${{ inputs.origin-branch }}" ]; then
        echo "branch_name=${{ github.ref_name }}" >> $GITHUB_ENV
      else
        echo "branch_name=${{ inputs.origin-branch }}" >> $GITHUB_ENV
      fi
      source $GITHUB_ENV
      echo "Using branch: $branch_name"
    shell: bash

  - run: |
      curl -o check_pull_head_branch \
      --url https://api.github.com/repos/${{ github.repository }}/pulls \
      --header "authorization: Bearer ${{ github.token }}" \
      --header "content-type: application/json"
      
      PULL_HEAD_BRANCH=$(cat check_pull_head_branch | jq -r --arg branch "$branch_name" '.[] | select(.head.ref == $branch) | .head.ref')
      
      if [ -n "$PULL_HEAD_BRANCH" ]; then
        echo "pull_head_branch=$PULL_HEAD_BRANCH" >> $GITHUB_ENV
      fi
    shell: bash  

  - run: |
      if [ -z "${{ env.pull_head_branch }}" ]; then
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pulls \
        --header "authorization: Bearer ${{ github.token }}" \
        --header "content-type: application/json" \
        --data '{
          "title": "${{ inputs.custom-title }} ${{ inputs.target-branch }} < ${{ env.branch_name }}",
          "body": "${{ inputs.custom-body }}",
          "head": "${{ env.branch_name }}",
          "base": "${{ inputs.target-branch }}"
        }' \
        --fail
        echo "Pull request has been created!"
      else 
        echo "There is already a Pull Request created from branch ${{ env.branch_name }} to branch ${{ inputs.target-branch }}"
      fi
    shell: bash
 