name: 'Create Pull Request'
description: 'Creates a pull request with changes'

inputs:
  token:
    description: 'GitHub Token'
    required: true
  branch:
    description: 'Branch name'
    required: true
  base:
    description: 'Base branch for the pull request'
    required: true
  commit_message:
    description: 'Commit message'
    required: true
  title:
    description: 'Title of the pull request'
    required: true
  body:
    description: 'Body of the pull request'
    required: true

runs:
  using: 'node20'
  main: 'index.js'

